[frontends]
  [frontends.frontend1]
    backend = "backend1"
    passHostHeader = true
    [frontends.frontend1.routes]
        [frontends.frontend1.routes.route0]
            rule = "Host:recette.myclient.com"

[backends.backend1]

    [backends.backend1.servers]
      [backends.backend1.servers.server0]
        url = "http://10.2.0.6:9001"
        weight = 1